[package]
name = "thingbuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ["alloc"]
alloc = []
default = ["std"]

[dependencies]

[dev-dependencies]
loom = { version = "0.5", features = ["checkpoint", "futures"] }
# So that we can use `poll_fn` in tests.
futures-util = "0.3"

[profile.test]
opt-level = 3

[patch.crates-io]
loom = { git = "https://github.com/tokio-rs/loom", branch = "eliza/thread-park"}