[package]
name = "thingbuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ["alloc"]
alloc = []
default = ["std"]

[dependencies]

[dev-dependencies]
loom = "0.5"

[profile.test]
opt-level = 3